default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: root
  pool: 5

development:
  <<: *default
  database: poc_tenant

test:
  <<: *adapter: 'postgresql'
# default: &default
#   adapter: postgresql
#   host: poc-multitenant.cxxmbla5slmc.us-east-2.rds.amazonaws.com
#   port: 5432
#   username: postgres
#   password: postgres

# development:
#   <<: *default
#   database: btc
